from zlm_zsc.zscript import ZScript, register_command
from zlm_zsc.base_commands import ZCommand, ZRoutine
from zlm_zsc import commands, base_commands

SubdivMax = register_command(commands.SubdivMax)
SubdivRestore = register_command(commands.SubdivRestore)
SubdivSet = register_command(commands.SubdivSet)
SubdivStore = register_command(commands.SubdivStore)
DeactivateRecord = register_command(commands.DeactivateRecord)
SetLayerMode = register_command(commands.SetLayerMode)
SetIntensity = register_command(commands.SetIntensity)
ExportLayer = register_command(commands.ExportLayer)
TextCommand = register_command(base_commands.TextCommand)
Quote = register_command(commands.Quote)
GetNumPoint = register_command(commands.GetNumPoint)
SetSubDivForVertex = register_command(commands.SetSubDivForVertex)
UpdateMesh = register_command(commands.UpdateMesh)
ExportMesh = register_command(commands.ExportMesh)
CreateLayer = register_command(commands.CreateLayer)
FocusLayer = register_command(commands.FocusLayer)
DeleteLayer = register_command(commands.DeleteLayer)
RenameLayer = register_command(commands.RenameLayer)
DuplicateLayer = register_command(commands.DuplicateLayer)
MoveLayer = register_command(commands.MoveLayer)
MergeDown = register_command(commands.MergeDown)
